services:
  strava2garmin:
    build: .
    container_name: strava2garmin
    restart: unless-stopped
    env_file:
      - ./app/.env
    volumes:
      - ./app/data:/app/data
      - ./app/activities:/app/activities
